% olsa_splashscreen - copyright and license information for custom procedure
% Version 1.30.0, last modified 01.03.2013 09:36

%------------------------------------------------------------------------------
% AFC for Mathwork’s MATLAB
%
% Author(s): Stephan Ewert
%
% Copyright (c) 1999-2013, Stephan Ewert. 
% Some rights reserved.
%
% This work is licensed under the 
% Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License (CC BY-NC-ND 3.0). 
% To view a copy of this license, visit
% http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to Creative
% Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
%------------------------------------------------------------------------------

function vlmatrix_splashscreen( mode )

%global def

% early out?
if ( exist('vlmatrixini.mat') == 2 )
    return;
end

if ( strcmp( mode,'accept' ) )
    ini = 2;
    % save MATLAB 4 compatible, so all 5,6,7 versions can read it
    save([fileparts(which(mfilename)), filesep, 'olsaini'],'ini','-V4');

    if ( findobj('Tag','vlmatrix_splashscreen'))
        close(findobj('Tag','vlmatrix_splashscreen'));
    end
    return;
end

colorblk = [0 0 0];
colorbase = [1 1 1];
colorstring = [0 0 0];

fposition = get(0,'defaultFigurePosition');
fposition(1:2) = fposition(1:2)+[fposition(3)-400 fposition(4)-400]/2;
fposition(3:4) = [400 400];

imagedata = imread('olsa_splashscreen.jpg');

h = figure('BusyAction','cancel',...			% create modal dialog window
   'Tag','olsa_splashscreen',...
   'menubar','none',...
   'Windowstyle', 'modal',...
   'Color',colorblk,...
   'Interruptible','off',...
   ... % added secure close
   ... % added Truetype
   'defaultUIControlFontname','Arial', ...
   'resize','off', ...
   'numbertitle','off', ...
   ... % change size once to avoid Matlab 6 modal window refresh bug
   'Name','About Oldenburg Sentence Test for AFC', ...
   'position',fposition - [0 0 1 1] );
   

% change to default size again
set(h,'position',fposition);
   

c=image(imagedata);
set(get(c,'parent'),'position',[0 0 1 1],'box','off', ...
   'xtick',[0 1],'ytick',[0 1],'xticklabel',' | ','yticklabel','      |      ')

b = uicontrol ...
   ('Parent',h, ...
   'Units','normalized', ...
	'FontUnits','normalized', ...
	'BusyAction','cancel', ...
   'Callback','olsa_splashscreen(''accept'')', ...
	'Position',[0.09 0.022 0.03 0.03], ...
	'Style','checkbox', ...
	'selectionhighlight','off', ...
	'backgroundColor',colorbase,...
	'foregroundColor',colorstring,...
   'Tag','splashscreen_checkbox');

% c = uicontrol ...
%    ('Parent',h, ...
%    'Units','normalized', ...
% 	'FontUnits','normalized', ...
% 	'BusyAction','cancel', ...
% 	'Position',[0.55 0.9 0.3 0.05], ...
% 	'FontSize',0.75, ...
% 	'Style','text', ...
% 	'HorizontalAlignment','left',...
% 	'string',def.version, ...
% 	'selectionhighlight','off', ...
% 	'backgroundColor',colorbase,...
% 	'foregroundColor',colorstring,...
%    'Tag','splashscreen_checkbox');
% 
% c = uicontrol ...
%    ('Parent',h, ...
%    'Units','normalized', ...
% 	'FontUnits','normalized', ...
% 	'BusyAction','cancel', ...
% 	'Position',[0.55 0.85 0.25 0.05], ...
% 	'FontSize',0.75, ...
% 	'Style','text', ...
% 	'HorizontalAlignment','left',...
% 	'string',def.versionDate, ...
% 	'selectionhighlight','off', ...
% 	'backgroundColor',colorbase,...
% 	'foregroundColor',colorstring,...
%    'Tag','splashscreen_checkbox');

% eof
